spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  messages:
    basename: i18n/messages

comment.avatar: /images/avatar.png

# pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  page-size-zero: true
  row-bounds-with-count: true


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.blog.entity
  configuration:
      local-cache-scope: statement

#阿里云 OSS
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      bucketname: travel-2021
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI4GDq7CtJGbJPAmU7VuTx
      keysecret: fQgWdmKHgjj3Nr07yugAL8Kfin0LRl